blog_api_create:
    path: /blog/api/create
    methods: [POST]
    defaults:
        _controller: BlogBundle:Blog:create

blog_api_modify:
    path: /blog/api/modify/{blogId}
    methods: [POST]
    defaults:
        _controller: BlogBundle:Blog:modify
    requirements:
        blogId:   \d+

blog_api_delete:
    path: /blog/api/delete/{blogId}
    methods: [DELETE]
    defaults:
        _controller: BlogBundle:Blog:delete
    requirements:
        blogId:   \d+