blog_front_end_list:
    path: /blog/list
    defaults:
        _controller: BlogBundle:FrontEnd:list

blog_front_end_read:
    path: /blog/read/{blogId}
    methods: [GET]
    defaults:
        _controller: BlogBundle:FrontEnd:read
    requirements:
        blogId:   \d+

blog_front_end_create:
    path: /blog/create
    defaults:
        _controller: BlogBundle:FrontEnd:create

blog_front_end_modify:
    path: /blog/modify/{blogId}
    defaults:
        _controller: BlogBundle:FrontEnd:modify
    requirements:
            blogId:   \d+

blog_front_end_delete:
    path: /blog/delete/{blogId}
    defaults:
        _controller: BlogBundle:FrontEnd:delete
    requirements:
            blogId:   \d+