UserBundle\Entity\User:
    type:  entity
    table: fos_user
    repositoryClass: UserBundle\Repository\AuthorRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO