UserBundle\Entity\UserLogin:
    type:  entity
    table: user_login_log
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToOne:
        user_Id:
            targetEntity: UserBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id
                onDelete: cascade
    fields:
        attempted_datetime:
            type: datetime