# src/BlogBundle/Resources/config/doctrine/Blog.orm.yml
BlogBundle\Entity\Blog:
    type: entity
    table:  SymfBlog_Blog
    repositoryClass: BlogBundle\Repository\BlogRepository
    id:
      id:
        type: integer
        generator: { strategy: AUTO }
    manyToOne:
      createdBy:
          targetEntity: UserBundle\Entity\User
          joinColumn:
              name: created_by
              referencedColumnName: id
              onDelete: cascade
    fields:
      name:
        type: string
        length: 50

      description:
        type: text
        nullable: true

      createdDate:
        type: datetime

      lastUpdatedDate:
        type: datetime

      lastPostedDate:
        type: datetime
        nullable: true

      isPublished:
        type: boolean